services:
  influx:
    image: influxdb:1.8
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 5s
      retries: 5
    restart: always

volumes:
  influxdb-data: