services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.4
    ports:
    #   - 8123:8123
      - 9001:9000
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      retries: 5
    restart: always

volumes:
  clickhouse-data: