data-source:
  file:
    location: ./devops-data.gz
  type: FILE
loader:
  db-specific:
    admin-db-name: postgres
    chunk-time: 8h0m0s
    create-metrics-table: true
    field-index: VALUE-TIME
    field-index-count: 1
    force-text-format: false
    host: localhost
    in-table-partition-tag: true
    log-batches: false
    partition-index: true
    partitions: 0
    pass: "postgres"
    port: "5432"
    postgres: sslmode=disable
    replication-factor: 0
    time-index: true
    time-partition-index: false
    use-hypertable: true
    use-insert: false
    use-jsonb-tags: false
    user: postgres
    write-profile: ""
    write-replication-stats: ""
  runner:
    batch-size: "10000"
    channel-capacity: "0"
    db-name: benchmark_devops
    do-abort-on-exist: false
    do-create-db: true
    do-load: true
    flow-control: false
    hash-workers: false
    insert-intervals: ""
    limit: "0"
    reporting-period: 10s
    seed: 0
    workers: "2"
  target: timescaledb
