services:
  mongo:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      retries: 5
    restart: always

volumes:
  mongodb-data: